# Generated by Django 5.2.13 on 2026-04-20 23:59

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='A unique UUID for this entry. This is auto-generated and cannot be changed.', unique=True, verbose_name='UUID')),
                ('title', models.CharField(help_text="The entry's title.", max_length=2048)),
                ('description', models.CharField(blank=True, default='', help_text="The entry's description. Should be short(er).", max_length=1024)),
                ('url', models.URLField(help_text="The entry's URL.", verbose_name='URL')),
                ('date_added', models.DateTimeField(auto_now_add=True, help_text='The datetime this entry was added to the webring.')),
                ('date_last_updated', models.DateTimeField(auto_now=True, help_text='The most recent datetime this entry was updated.')),
                ('is_dead', models.BooleanField(default=False, help_text='Indicate if this entry is dead (i.e., cannot be accessed anymore.)', verbose_name='Entry is dead?')),
                ('is_web_archive', models.BooleanField(default=False, help_text="Indicate if this entry's URL is now pointed to The Web Archive.", verbose_name='Entry redirects to Web Archive?')),
            ],
            options={
                'verbose_name_plural': 'Entries',
                'db_table_comment': 'Store the entries for an individual webring.',
            },
        ),
        migrations.CreateModel(
            name='Webring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='A unique UUID for this webring. This is auto-generated and cannot be changed.', unique=True, verbose_name='UUID')),
                ('name', models.CharField(help_text="The webring's name.", max_length=512)),
                ('url', models.URLField(help_text='The URL of the webring.', verbose_name='URL')),
                ('author', models.CharField(blank=True, default='', help_text='The primary author of the webring.', max_length=512)),
                ('maintainer', models.CharField(blank=True, default='', help_text='The primary maintainer of the maintainer.', max_length=512)),
                ('api_key', models.CharField(blank=True, default=uuid.uuid4, help_text='The admin API key for accessing protected routes.', max_length=512, verbose_name='Admin API key')),
                ('is_active', models.BooleanField(default=True, help_text='Indicate if this webring is live, meaning it can be viewed and traversed.')),
            ],
            options={
                'db_table_comment': 'Store the individual webring instances being run on this app.',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, help_text='The datetime this check occurred.')),
                ('url', models.URLField(help_text='The URL checked.')),
                ('was_alive', models.BooleanField(default=True, help_text='Was the URL alive at the time of this check?', verbose_name='URL was alive?')),
                ('message', models.TextField(default='', help_text='Any message generated during the check.')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.entry')),
            ],
            options={
                'verbose_name': 'Entry history',
                'verbose_name_plural': 'Entry histories',
                'db_table_comment': 'Audit log of linkrot checks.',
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='instance',
            field=models.ForeignKey(help_text='The webring this entry belong to.', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.webring'),
        ),
    ]
