# Generated by Django 5.2.14 on 2026-05-16 01:33

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid7,
                help_text="A unique UUID for this entry. This is auto-generated and cannot be changed.",
                unique=True,
                verbose_name="UUID",
            ),
        ),
    ]
