# Generated by Django 5.2.13 on 2026-05-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="webring",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="A brief description of the webring's purpose or intention.",
            ),
        ),
    ]
