# Generated by Django 5.2.13 on 2026-04-21 01:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("core", "0001_initial")]

    operations = [
        migrations.RenameModel(
            old_name="History",
            new_name="LinkrotHistory",
        ),
    ]
