# Generated by Django 5.2.14 on 2026-05-16 02:32

import django.db.models.deletion
import secrets
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0002_alter_entry_uuid")]

    operations = [
        migrations.AlterModelTableComment(name="entry", table_comment=None),
        migrations.AlterModelTableComment(name="webring", table_comment=None),
        migrations.RemoveField(model_name="webring", name="api_key"),
        migrations.CreateModel(
            name="WebringAPIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        default=secrets.token_hex,
                        help_text="An API key for accessing protected routes for this webring.",
                        max_length=512,
                        verbose_name="Admin API key",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Indicate if this API key is active and can be used to access protected routres",
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        help_text="The webring this API key belong to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="core.webring",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
