# Generated by Django 5.2.14 on 2026-05-16 02:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0003_alter_entry_table_comment_and_more")]

    operations = [
        migrations.AddField(
            model_name="webringapikey",
            name="date_added",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="The datetime this API key was created.",
            ),
            preserve_default=False,
        ),
    ]
