# Generated by Django 5.2.14 on 2026-05-09 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("core", "__first__")]

    operations = [
        migrations.CreateModel(
            name="LinkrotHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_added",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The datetime this check occurred."
                    ),
                ),
                ("url", models.URLField(help_text="The URL checked.")),
                (
                    "was_alive",
                    models.BooleanField(
                        default=True,
                        help_text="Was the URL alive at the time of this check?",
                        verbose_name="URL was alive?",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        default="", help_text="Any message generated during the check."
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="core.entry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entry history",
                "verbose_name_plural": "Entry histories",
                "db_table_comment": "Audit log of linkrot checks.",
            },
        ),
    ]
