# Generated by Django 5.2.14 on 2026-05-16 02:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("linkrot", "0001_initial")]

    operations = [
        migrations.AlterModelTableComment(name="linkrothistory", table_comment=None),
    ]
